### ISSUE TITLE
[Contribution] [iOS] Firebase Crashlytics

### ISSUE THREAD

**Issue by vhugogarcia** [Redth/DotNet.Platform.SlimBindings#8]
**[Firebase Crashlytics](https://firebase.google.com/docs/crashlytics)** is a lightweight, realtime crash reporter that helps you track, prioritize, and fix stability issues that erode our app quality.

**Progress made:**
I have been able to create a new XCode project called: MauiFirebaseCrashlytics, then I created the binding and updated the sample application.

I'm facing the following issues:

- On iOS, the SDK is not starting up correctly, I keep getting the following error message:
```
Crashlytics could not find the symbol for the app's main function and cannot start up. This can be resolved 2 ways depending on your setup:
1. If you have Exported Symbols File set in your Build Settings, add "__mh_execute_header" as a newline in your Exported Symbols File.
2. If you have -exported_symbols_list in your linker flags, remove it.
```
- When trying to debug on a physical device (iOS), I get the following error: 
```
Undefined symbols for architecture arm64:
    "_OBJC_CLASS_$_FirebaseCrashlytics", referenced from:
        objc-class-ref in registrar.o
  ld: symbol(s) not found for architecture arm64
```
 
For the first error, I following these recommendations from our friend @rolfbjarne  https://github.com/xamarin/xamarin-macios/issues/19157#issuecomment-1798534439 by adding the `<_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>` without luck.
 
 I committed my changes to a branch on my fork, once I finish the implementation and do some code clean up, I will be happy to create a PR:
https://github.com/vhugogarcia/DotNet.Platform.SlimBindings/tree/firebase-crashlytics

@Redth @aritchie do you have any insight about the issues, I'm facing? 😃 

Thanks in advance

**Comment by aritchie** [comment]
Hi @vhugogarcia  - crashlytics has many issues beyond just the binding.  .NET stack traces are awful on firebase because it simply wasn't designed for them.  

If you choose to continue the binding because it works for you, that's absolutely fine.  

There are a few things I see in your native project that don't follow what we're working with.  We aren't using the xcframeworks directly.  We're using swift package manager which pulls in all the native stuff we need.  We also remove anything specific to analytics and linked that in our binding.

**Comment by vhugogarcia** [comment]
Thanks @aritchie for the feedback! I noticed the XCode project has been merged into a Single project. So, I will update my GitHub fork and start from zero again. 

I hope I can get it working soon with slim bindings 😎👍🏻.

**Comment by PavloLukianets** [comment]
@vhugogarcia did u manage to get it working? I did all the slim bindings part in our other separate project with no problems, however after uploading the dSYMS i still see no crashes, nor fatal errors.

> .NET stack traces are awful on firebase because it simply wasn't designed for them.

BTW @aritchie what do u recommend as AppCenter crashlytics substitute? All the other stuff that Microsoft recommends or something else like Sentry?

**Comment by aritchie** [comment]
@PavloLukianets use Sentry

**Comment by vhugogarcia** [comment]
@PavloLukianets a couple of weeks ago I created an article explaining the differences and why it is recommended Sentry. https://dev.to/vhugogarcia/mastering-error-insights-in-net-maui-sentry-vs-firebase-crashlytics-5aj3 I hope you find it useful. 

😎👍

**Comment by JoacimWall** [comment]
Hi
Sorry for hijacking this thread but I feel like I've almost tried everything.

I have one question, has you found any solution New relic/Sentry/Firebase that support and show the exact line number for MAUI handeld dotnet crash?

I only get the function name.

Sentry:
dotnet publish myProject.csproj -f net9.0-ios -c Release -p:RuntimeIdentifier=ios-arm64 -p:BuildIpa=True -o ./artifacts -p:SentryOrg=Myorg -p:SentryProject=myProj -p:SentryUploadSymbols=true -p:SentryUploadSources=true -p:SentryAuthToken=sentryxxx… 

if I then check for the uuid in my dSYM file on the mac i see this:
dwarfdump --uuid LibresseClub.app.dSYM
UUID: 572E7479-9446-315F-810F-626E7DA5648A (arm64) LibresseClub.app.dSYM/Contents/Resources/DWARF/LibresseClub

but the error still say no debug information could be found(se image).

If I navigate to Debug Information files under project settings
I see that the 572E7479-9446-315F-810F-626E7DA5648A file exist (se image)

![Image](https://github.com/user-attachments/assets/56aa60af-7303-43f2-a8a4-dcfa12a87280)

New relic:
After 3 months with questions and reports back and forth with the support there developers answers the they not supporting this for MAUI. There UI get error when we try to upload dsym file but the same files work on Firebase Crashlytics to upload.

![Image](https://github.com/user-attachments/assets/2017dabb-df2e-4a4e-9814-3d5817029b3e)
 
Firebase:
validate the id of the dsymfile
dwarfdump --uuid LibresseClub.app.dSYM
UUID: 42BEEBC8-34E1-3507-A0E1-495966035EE3 (arm64) LibresseClub.app.dSYM/Contents/Resources/DWARF/LibresseClub

If I upload the dsym file from azure build then:
The file get green and status version unknown. 
the I generate a error and the red line get added is this a missing pdf file?
![Image](https://github.com/user-attachments/assets/c2bf9994-53f7-4238-b3fc-a4c6d0af5667)

I see the reported error but not he line number.

//Joacim
